version: "3"

services:
  
  mongodb:
    image: mongo:4.0
    container_name: amax.exp.mongo
    restart: always
    volumes:
      - ./mongo:/data/db
    ports:
      - "27018:27017"
        #environment:
        #- MONGO_INITDB_ROOT_USERNAME=root
        #- MONGO_INITDB_ROOT_PASSWORD=test123

  amaxweb:
    build:
      context: ./docker
      dockerfile: Dockerfile.web
    container_name: amax.exp.web
    ports: 
      - 3039:3039
    restart: always

  amaxsrv:
    build:
      context: ./docker
      dockerfile: Dockerfile.srv
    container_name: amax.exp.srv
    ports: 
      - 9615:9615
    restart: always
